<%@ WebHandler Language="C#" Class="ApiShippingQuote" %>
using System;using System.Data.SqlClient;using System.Web;using HighExpertStore;
public class ApiShippingQuote:IHttpHandler{
public void ProcessRequest(HttpContext c){c.Response.ContentType="application/json";try{
string token=c.Request["token"]??"";string cep=(c.Request["cep"]??"").Trim();if(cep.Length<5){c.Response.StatusCode=400;c.Response.Write(Db.Json(new{error="CEP inválido"}));return;}
using(var conn=Db.GetConnection()){conn.Open();var uid=Db.ValidateToken(token,conn);if(uid==null){c.Response.StatusCode=401;c.Response.Write(Db.Json(new{error="Token inválido"}));return;}
int cartId=0;using(var cmd=new SqlCommand(@"SELECT TOP 1 Id FROM Carts WHERE UserId=@u AND Status='Active' ORDER BY Id DESC",conn)){cmd.Parameters.AddWithValue("@u",uid.Value);var x=cmd.ExecuteScalar();if(x==null){c.Response.StatusCode=400;c.Response.Write(Db.Json(new{error="Carrinho vazio"}));return;}cartId=Convert.ToInt32(x);}
int weight=0;using(var w=new SqlCommand(@"SELECT SUM(ISNULL(p.EstimatedWeightGrams,200)*ci.Quantity) FROM CartItems ci JOIN Products p ON p.Id=ci.ProductId WHERE ci.CartId=@c",conn)){w.Parameters.AddWithValue("@c",cartId);var v=w.ExecuteScalar();weight=v==DBNull.Value||v==null?0:Convert.ToInt32(v);}
decimal baseP;char f=cep[0];switch(f){case '0':case '1':baseP=19.90m;break;case '2':case '3':baseP=24.90m;break;case '4':case '5':case '6':baseP=29.90m;break;case '7':baseP=34.90m;break;case '8':baseP=39.90m;break;default:baseP=49.90m;break;}
var steps=Math.Max(0,(weight-500)/500);decimal ship=baseP+steps*4.50m;c.Response.Write(Db.Json(new{cep=cep,weightGrams=weight,shipping=Math.Round(ship,2)}));}}catch(Exception ex){c.Response.StatusCode=500;c.Response.Write(Db.Json(new{error=ex.Message}));}}public bool IsReusable{get{return false;}}}